name: Veracode-SAST
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-2019
 
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
      - name: Restore dependencies
        run: nuget restore Verademo-dotnet.sln
      - name: Clean Default Build
        run: 'msbuild Verademo-dotnet.sln /t:clean'
      - name: Build - was dotnet build --no-restore
        run: >-
          msbuild.exe Verademo-dotnet.sln /p:DeployOnBuild=true
          /p:WebPublishMethod=Package /p:PackageAsSingleFile=true
          /p:SkipInvalidConfigurations=true /p:PackageLocation=./..
          /p:DebugSymbols=true /t:build
      - name: List files in the repository and copy artifact
        run: |
          dir ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}/artifact
          copy Verademo-dotnet.zip ${{ github.workspace }}/artifact
          dir ${{ github.workspace }}/artifact
    
  Security:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Check out Main
          uses: actions/checkout@v2
          with:
            path: '${{ github.workspace }}/artifact/Verademo-dotnet.zip'
        - name: Veracode Upload And Scan
          uses: veracode/veracode-uploadandscan-action@0.2.4
          with: 
            appname: GitHub_VerademoDotNet
            createprofile: false
            filepath: '${{ github.workspace }}/artifact'
            vid: '${{ secrets.Veracode_API_ID }}'
            vkey: '${{ secrets.Veracode_API_KEY }}'
          
            
            
      
