name: Veracode-SAST
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-2019
 
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
      - name: Restore dependencies
        run: nuget restore Verademo-dotnet.sln
      - name: create build directory
        run: mkdir _build
      - name: Clean Default Build
        run: 'msbuild Verademo-dotnet.sln /t:clean'
      - name: Build - was dotnet build --no-restore
        run: >-
          msbuild.exe Verademo-dotnet.sln /p:DeployOnBuild=true
          /p:WebPublishMethod=Package /p:PackageAsSingleFile=true
          /p:SkipInvalidConfigurations=true /p:PackageLocation=./..
          /p:DebugSymbols=true /t:build
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: VerademoBundle
          path: "./_build"
      - name: package
        run: Compress-Archive -LiteralPath _build/ -DestinationPath BuildArchive.zip
        
      - run: ls
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: VerademoZip
          path: "./BuildArchive.zip"
    

          
            
            
      
