name: Veracode Pipeline Scanner

on: 
  push:
    branches: main

jobs: 
  build: 
    runs-on: ubuntu-latest
  
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      
      - name: GitHub Script
        run: echo ${GITHUB_WORKSPACE}
      
      - name: see content
        run: ls -la
    
      - name: Restore dependencies
        run: dotnet restore /home/runner/work/VerademoDotNet/VerademoDotNet/VerademoDotNet/Verademo-dotnet.csproj
  
    
  
  
          
        
      
  
