name: Veracode-Pipeline
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: see who am
        run: whoami
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
      - name: Restore dependencies
        run: nuget restore Verademo-dotnet.sln
      - name: Clean Default Build
        run: 'msbuild Verademo-dotnet.sln /t:clean'
      - name: Build - was dotnet build --no-restore
        run: >-
          msbuild.exe Verademo-dotnet.sln /p:DeployOnBuild=true
          /p:WebPublishMethod=Package /p:PackageAsSingleFile=false
          /p:SkipInvalidConfigurations=true /p:PackageLocation=./..
          /p:DebugSymbols=true /t:build /p:platform="Any CPU" /p:configuration="Debug"
       # Upload the artifact of the zip archive
       
      - name: List files in repo and zip artifact
        run: |
          dir ${{ github.workspace }}
          Compress-Archive -Path ${{ github.workspace }} -DestinationPath Verademo-dotnet.zip
      - run: ls
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: VerademoZip
          path: "${{ github.workspace }}/Verademo-dotnet.zip"
          
      - name: Veracode Pipeline-Scan
        # You may pin to the exact commit or the version.
        # uses: veracode/Veracode-pipeline-scan-action@35aecef76c5365b8dea83c150852cdebc0991d2d
        uses: veracode/Veracode-pipeline-scan-action@v1.0.10
        with:
          # vid
          vid: ${{ secrets.VERACODE_API_ID }}
          # vkey
          vkey: ${{ secrets.VERACODE_API_KEY }}
          # Filename of the packaged application to upload and scan.
          file: ./Verademo-dotnet.zip
          # GITHUB_TOKEN or a repo scoped PAT.
          
