name: .5-SAST-Check-Pull-Request-or-Branch

on:
  workflow_dispatch:

jobs:
  Pipeline_Scan:

    runs-on: windows-2022

# Checkout-Build-Artifact

    steps:
    - uses: actions/checkout@v3

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1.3

# This builds the app and creates a ZIP file of the applicaitons    
    - name: Run msbuild
      run: |
          msbuild Verademo-dotnet.sln /p:DeployOnBuild=true
